services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    
    image: frontend-reto
    container_name: frontend-reto
    ports:
      - 3000:${PORT}
    environment:
      APP_VERSION: ${APP_VERSION}
      PORT: ${PORT}
      GEMINI_MODEL: ${GEMINI_MODEL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      
